### ISSUE TITLE
Intl.Segmenter does not exist

### ISSUE THREAD

**Issue by vshakitskiy** [QuiiBz/ogstudio#19]
Going to `ogstudio.app` will cause this message:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/ffd89d69-4100-4f98-b2a7-f73a23d56dd5)

Running the app locally will show error, related to Satori:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/ebf4a763-b511-424b-904b-849d54a49a7c)

**Comment by QuiiBz** [comment]
What's your browser version? It should be supported in all latest browsers: https://caniuse.com/mdn-javascript_builtins_intl_segmenter

But we should probably add a banner instead of crashing in this case.

**Comment by QuiiBz** [comment]
Will be fixed in #18, it just shows a toaster and prevents rendering any preview or exporting to SVG/PNG:

<img width="1060" alt="Screenshot 2023-12-28 at 15 12 08" src="https://github.com/QuiiBz/ogstudio/assets/43268759/5865798b-f22a-4fcd-ac29-ea37775fc07b">

**Comment by vshakitskiy** [comment]
My Firefox browser version is not supported, thats the issue. 122.0b3
