### ISSUE TITLE
Better color picker

### ISSUE THREAD

**Issue by QuiiBz** [QuiiBz/ogstudio#26]
We currently use the browser's color picker, which works fine but is very limited:

<img width="265" alt="Screenshot 2023-12-29 at 17 16 38" src="https://github.com/QuiiBz/ogstudio/assets/43268759/c7adcab7-bd4f-432e-a19c-cb9e3a452ea2">

Ideally, we'd want to group solid color, gradients, and opacity in the same popup (same as Figma). It should also work the same for text elements, but we'll have to figure out first how to render gradient texts with Satori.

**Comment by QuiiBz** [comment]
This seems interesting: https://react-spectrum.adobe.com/react-aria/useColorArea.html

**Comment by vshakitskiy** [comment]
Good idea. Some of browsers like mine is showing pretty unstyled popup there:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/8c23c3cc-bae3-4955-91d7-bc4c44536f43)
