### ISSUE TITLE
Use `clsx` to handle optional classes

### ISSUE THREAD

**Issue by QuiiBz** [QuiiBz/ogstudio#29]
We have many places where we add optional classes based on some conditions: https://github.com/search?q=repo%3AQuiiBz%2Fogstudio+className%3D%7B%60&type=code

This is kinda ugly and sometime results in `undefined` or ` ` in the resulting className. Let's use [clsx](https://github.com/lukeed/clsx) instead.

**Comment by Willem-Jaap** [comment]
Suggestion: clsx in combination with tailwind-merge like in shadcn/ui: 
```tsx
import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
    return twMerge(clsx(inputs))
}
```
https://github.com/shadcn-ui/ui/blob/6b523b60db268e20c1793a26db8d92782d845538/apps/www/lib/utils.ts#L6C1-L6C1
