### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by vshakitskiy** [QuiiBz/ogstudio#36]
While working with code, I saw that in files we use single and double quotes, and at the same time place and not place semicolons. Will it be relevant now if I'll set eslint and fix all code to single quotes and always semicolons?

**Comment by QuiiBz** [comment]
We already have an eslint config, but it doesn't have formatting rules: https://github.com/QuiiBz/ogstudio/tree/main/packages/eslint

I wanted to setup [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier) but haven't got time yet. I'd also like to try [Biome](https://github.com/biomejs/biome) to replace both eslint & prettier, but it might need more work.

**Comment by QuiiBz** [comment]
Done in https://github.com/QuiiBz/ogstudio/pull/39
