### ISSUE TITLE
Undo/Redo button cause application error

### ISSUE THREAD

**Issue by vshakitskiy** [QuiiBz/ogstudio#53]
Making undo/redo using Ctrl + z/Z  works fine. But, using undo button on the left pannel cause application error. Here's the console:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/cbde0230-c1e1-4740-9711-e4e0b5c9db8a)

**Comment by QuiiBz** [comment]
Yeah I've seen that one, it's so strange. Works perfectly fine with ctrl+z/Z but doesn't on the buttons 🤯

**Comment by vshakitskiy** [comment]
If we place undo/redo functions inside another function, it won't cause an error:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/cd88741b-7498-4e55-be6d-43862f6a5a7a)

**Comment by vshakitskiy** [comment]
Fixed in #52
