### ISSUE TITLE
Elements moving out of view

### ISSUE THREAD

**Issue by vshakitskiy** [QuiiBz/ogstudio#9]
Placing element at the left and top edges of the screen working fine:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/b1129b0b-661b-4021-8b92-1b7bc583d00c)

However, when placing element at the right and bottom edges of the screen can cause expansion of the window:

![изображение](https://github.com/QuiiBz/ogstudio/assets/54102609/67f44bc1-10a6-46a0-9a9a-2ba29f678a69)

**Comment by QuiiBz** [comment]
Good catch, let me know if you'd like to fix it (I think we just need to prevent overflow on the whole editor)

**Comment by vshakitskiy** [comment]
Yea, I'll fix it right now!
